# Point GOPATH to the correct location.
export GOPATH="${HOME}/go"

# Add Go binaries to PATH.
export PATH="${GOPATH}/bin:${PATH}"

# Enable the json/v2 experimental feature.
export GOEXPERIMENT='jsonv2'
