# espanso configuration file

matches:
  - trigger: ";--"
    replace: "—"

  - trigger: ";shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ";fliptable"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: ";>"
    replace: "→"

  - trigger: ";<"
    replace: "←"
