#!/usr/bin/env bash

sandbox-exec -p '(version 1)(allow default)(deny network*))' \
  w3m \
  -I UTF-8 -O UTF-8 -T text/html \
  -s -graph \
  -o fold_textarea=true \
  -o fold_line=true \
  -o decode_url=true \
  -o display_link=true \
  -o display_image=false
