import = [
  "~/.config/alacritty/theme.d/adwaita.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Blex Mono Nerd Font"

[font.bold]
family = "Blex Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Blex Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Blex Mono Nerd Font"
style = "Italic"

[colors]
draw_bold_text_with_bright_colors = true
