[james@cipher.host]
source            = imaps://james%40cipher.host@imap.migadu.com:993
outgoing          = smtps+plain://james%40cipher.host@smtp.migadu.com:465
source-cred-cmd   = security find-generic-password -w -s 'james@cipher.host'
outgoing-cred-cmd = security find-generic-password -w -s 'james@cipher.host'
default           = INBOX
from              = James Pond <james@cipher.host>
aliases           = James Pond <root@jamespond.co>
copy-to           = Sent
signature-file    = ~/.config/aerc/signatures/jamesatcipherdothost
pgp-auto-sign     = true
pgp-opportunistic-encrypt = true
check-mail        = 2m

[ops@cipher.host]
source            = imaps://ops%40cipher.host@imap.migadu.com:993
outgoing          = smtps+plain://ops%40cipher.host@smtp.migadu.com:465
source-cred-cmd   = security find-generic-password -w -s 'ops@cipher.host'
outgoing-cred-cmd = security find-generic-password -w -s 'ops@cipher.host'
default           = INBOX
from              = DevOps Team at Cipher Host <ops@cipher.host>
copy-to           = Sent
check-mail        = 2m
