# General configuration file for Bash.

# Use vi key bindings for bash instead of emacs ones.
set -o vi

# Checks that a command found in the hash table exists before trying to
# execute. If a hashed command no longer exists, a normal path search is
# performed.
shopt -u checkhash

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the history file, do not overwrite it.
shopt -s histappend

# Move history file to XDG_STATE_HOME.
export HISTFILE="${XDG_STATE_HOME}/bash/history"

# Keep all commands in the history file.
export HISTSIZE=-1
export HISTFILESIZE=-1

# Do not put duplicate lines or lines starting with space in the history file.
export HISTCONTROL='ignoreboth'

# Prevent certain commands from being added to the history file.
export HISTIGNORE='cd*:ls*:pwd:exit:clear:history*:aerc:htop'

# Add date and time to bash history in the ISO8601 format.
export HISTTIMEFORMAT='[%y-%m-%d %T] '

# Write commands to history right away.
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"

# Disable session history.
export SHELL_SESSION_HISTORY=0

# Source user-defined settings.
for config_file in "${BASH_CONFIG_HOME}"/conf.d/*.conf; do
  source "${config_file}"
done
